In [2]:
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [13]:
list1 = []
list2 = []
for i in range(5):
    it1 = int(input('enter to print in list1\n'))
    it2 = int(input('Enter to print in list2\n'))
    list1.append(it1)
    list2.append(it2)
print(list1)
print(list2)
print()
arra = np.array([list1,list2])
print(arra)
arra1 = arra.reshape(1,10)
print(arra1)
arra1.sort()
print(arra1)
arranew = arra1.reshape(2,5)
arranew


enter to print in list1
2
Enter to print in list2
1
enter to print in list1
4
Enter to print in list2
5
enter to print in list1
3
Enter to print in list2
0
enter to print in list1
9
Enter to print in list2
7
enter to print in list1
66
Enter to print in list2
11
[2, 4, 3, 9, 66]
[1, 5, 0, 7, 11]

[[ 2  4  3  9 66]
 [ 1  5  0  7 11]]
[[ 2  4  3  9 66  1  5  0  7 11]]


array([[ 0,  1,  2,  3,  4,  5,  7,  9, 11, 66]])

In [17]:
import numpy as np
arra1 = np.arange(10)
print(arra1)
print()
arra2 = arra1.reshape(2,5)
print(arra2)
print('size of array is ')
print(arra2.size)
print('dimensions of array are ')
print(arra2.ndim)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
size of array is 
10
dimensions of array are 
2


In [21]:
array1 = np.array([2,34,4,5,2,445])
print(array1)
array2 = array1.reshape(2,3)
print()
print(array2)


[  2  34   4   5   2 445]

[[  2  34   4]
 [  5   2 445]]


In [25]:
array1 = np.array([[1,2],
                   [3,4]])

array2 = np.array([[5,6],
                   [7,8]])

print('The vertical stack is\n',np.vstack((array1,array2)))
      
print('\nThe Horizontal stack is\n',np.hstack((array1, array2)))

The vertical stack is
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

The Horizontal stack is
 [[1 2 5 6]
 [3 4 7 8]]


In [30]:
def unique_value(list1):  
    unique_list = [] 
    for x in list1: 
        if x not in unique_list: 
            unique_list.append(x) 
    for x in unique_list: 
        print(x)
      
list1 = [10, 20, 20, 30, 40, 40] 
print("the unique values from 1st list is") 
unique_value(list1) 
list1 = [10, 20, 20, 30, 40, 40]
l1 = [] 
count = 0
for item in list1: 
    if item not in l1: 
        count += 1
        l1.append(item) 
print("No of unique items are:", count) 

the unique values from 1st list is
10
20
30
40
No of unique items are: 4
